### ISSUE TITLE
Pinch to zoom gesture, lock button

### ISSUE THREAD

**Issue by Github-com-foss** [moneytoo/Player#1]
It is the One of the best video player i been use. Now a days dont want advanced player (VLC) because of Phone hardware. So simple video player will do best in phone nowadays i love It is simplistic and minimal. And it can contain all features. Good Work.
My only Suggestion is
1. Remove pitch to zoom button and replace to gesture pitch to zoom.
2. Add video lock option, if add (replace video lock button to pitch to zoom place) 
![N_1_1_1](https://user-images.githubusercontent.com/75672019/102684077-8b06af80-41fb-11eb-9b9d-9fecd9bf55ce.jpg)

**Comment by moneytoo** [comment]
I agree that pinch to zoom gesture would be useful as I often used it with other players because of various ultra wide content - especially when video is also letterboxed.

Could you elaborate more on the lock button - what is your use case, for what scenario you need that? I personally never found that much useful.

**Comment by Github-com-foss** [comment]
Lock and unlock option only. (Press to lock press to unlock ) it helps to reduce accidental touch while watching movies.

**Comment by Pranab009** [comment]
Please add this feature.

**Comment by moneytoo** [comment]
Track locking in #28
