### ISSUE TITLE
[Request] Android TV interface 

### ISSUE THREAD

**Issue by VuzzyM** [moneytoo/Player#127]
Add interface for android tv. 
Example:

![A16CObeBw-L](https://user-images.githubusercontent.com/66425682/123097465-d6af4580-d438-11eb-9d46-e8f2ee3c6755.png)

![screen-0](https://user-images.githubusercontent.com/66425682/123099820-33abfb00-d43b-11eb-9575-8e9071747b33.jpg)

**Comment by moneytoo** [comment]
Just Player currently leverages ExoPlayer's default UI (with a few tweaks), which is usable on both Android and Android TV devices. I may replace the file chooser with special Leanback themed browser but I don't really plan on making any other platform specific redesigns.

**Comment by Pentaphon** [comment]
@moneytoo If you commit to a full leanback UI for AndroidTV, people are then going to be asking for DLNA and SMB support since Android TV boxes have very little internal storage, which would make this player very similar to Nova Video Player. You may want to think about what you want this player to be and where you want to draw a line on what features you are willing to put time into in the long run.

**Comment by moneytoo** [comment]
@Pentaphon You're absolutely right. I believe I'm pretty strict with changes/features as the priority is basically to only satisfy my needs with a player I'm able to maintain in the long term. However I also like to learn & code so I from time to time, I may also add independent features that are basically plug and play (like the auto frame frate matching). Something like leanback file chooser sounds independent enough and I'm planning on at least testing libraries like this: https://github.com/ITVlab/TvFilePicker I also do not rule out SMB support if that's just one library to add that wouldn't require much other gluing.

**Comment by Pentaphon** [comment]
> I also do not rule out SMB support if that's just one library to add that wouldn't require much other gluing.

Sounds cool, moneytoo. just making wanted to make sure you're happy first and foremost, while making us happy with your player. Many projects have died from people simply asking too much from the dev and the dev taking on too much work due to pressure from the community. Looking forward to see where you take Just Player on your terms. Cheers.

**Comment by moneytoo** [comment]
I'm afraid I won't be implementing any TV/leanback interface any time soon. I have only one old crappy Android TV box and no TV so connecting it to my primary monitor or projector isn't much fun. Therefore I don't think I would be able to create something solid when I wouldn't even use it.
