### ISSUE TITLE
[Feature Request] Show only folders with videos and videos

### ISSUE THREAD

**Issue by RickyM7** [moneytoo/Player#13]
As in MX Player, it would be very useful if the app's homepage showed folders with videos and videos, both internal and external memory. This would make it easier to search for videos and make everything simpler.

| Example |
| :---: |
| ![mx](https://user-images.githubusercontent.com/24703825/103412390-a35bc000-4b53-11eb-851f-95cc230ea9dd.png) |.

**Comment by moneytoo** [comment]
The system file chooser is able to list all folders containing videos as well as access the whole device structure. My initial idea was to use this player app together with file manager app only (but due to not persistent file access I was forced to use file chooser). It would definitely be nice to have integrated manager but the ultimate goal could be media library done right (like in  [Infuse](https://firecore.com/infuse) for iOS which has probably the best video player UX I have encountered).

**Comment by RickyM7** [comment]
@moneytoo Got it.

**Comment by moneytoo** [comment]
Realistically speaking I will probably never get to finishing media library UI. However if there will ever be any open source media/video picker/chooser/browser library that is no worse (and nice looking) than the current system chooser and supports Storage Access Framework (no legacy storage), I will use that.

**Comment by RickyM7** [comment]
@moneytoo I'm not a programmer so I don't know what you're looking for on technical requirements, but maybe this [repo](https://github.com/AnilFurkanOkcun/UWMediaPicker-Android) will help with something. In case I find other interesting repos I comment here or edit the issue.

**Comment by divyansh10101** [comment]
No i would prefer current one to be best(without file chooser) as only this player is providing this file choosing bro try to stick to this system.

**Comment by moneytoo** [comment]
FYI: If you want an alternative file chooser, you may want to try [Material Files](https://github.com/zhanghai/MaterialFiles). It has some nifty features, though it doesn't support starting the file chooser [from specific directory](https://github.com/zhanghai/MaterialFiles/issues/440).
This is the only file manager that handles `ACTION_OPEN_DOCUMENT` and serves as a file chooser (and therefore works with Just Player) I know of. Let me know if you find any other compatible file manager.

**Comment by MercerBoi** [comment]
Ah man, so an in-built media library is most likely not happening? Having all your media folders across the phone in one place sounds extremely convenient as opposed to using the system file manager to pick and choose what you want to see. This app could've been my primary video player had it not been for the absence of this feature. This is more of an expression of my bafflement than a complaint. I'll still use this for playing media from links (since I don't trust MX with my internet connection), but it's a really tantalizing feeling to have an app as good looking and feature rich as this, but without a library.

I tried VLC but it's not as smooth and lacks certain polishes, so now I'm stuck between this and MX. Oh well, that's life.

**Comment by moneytoo** [comment]
@MercerBoi As I already wrote in https://github.com/moneytoo/Player/issues/13#issuecomment-752985960 - as is, the system file chooser already has a view listing media folder from across the whole device. It also shows video thumbnails and you always start in location of the last played video. What would be the benefit of an own library, except for a fine tuned and styled GUI?

Also, accessing all media folders is not as easy. On new Android versions, you can only access folders granted by the user so it would require management of these folders. (As relying on files indexed by media store may not work good enough)

However you can use Just Player and have a media library now ;-). I read that some users choose to use [Nova Video Player](https://github.com/nova-video-player/aos-AVP) and its option "Allow using another video player". It seems to work pretty well, including things like network storages (SMB, UPnP etc.).

**Comment by MercerBoi** [comment]
Hey, thanks for the response.

>the system file chooser already has a view listing media folder from across the whole device. It also shows video thumbnails and you always start in location of the last played video.

I'm embarassed to admit I hadn't explored this option before. Is there a way I can get the system file chooser to ignore the presence of .nomedia files? I keep my movies hidden so that they don't pop up if I'm trying to upload pics to chat apps like Discord or Messenger.

**Comment by moneytoo** [comment]
I'm "afraid" I'm will have to create some custom media chooser anyway. Because right now, there's no system file chooser on Android TV and the one currently used ([android-file-chooser](https://github.com/hedzr/android-file-chooser/)) doesn't really work on Android TV 11 (when targeting Android 11 #148).

The first idea is to integrate various file chooser libraries in Just Player and let users stick with what works best for them. Unfortunately, there isn't a lot maintained libraries that would work with non touch input and be suitable for listing movies (showing full file name is more important than all black thumbnail). If this wasn't enough, the Android TV 11 requires the use of MediaStore. So currently I know only of these options:

- [android-file-chooser](https://github.com/hedzr/android-file-chooser/) - MediaStore support in beta, build from 2019/10, too short file names
- [MediaFacer](https://github.com/CodeBoy722/MediaFacer) - Less suitable for selecting movies than android-file-chooser (thumbnails without file names)

So I will try creating some own video chooser using MediaStore and start with the simplest design. It should still be just another alternative to existing choosers (but maybe it could be optionally integrated more prominently).

Some other notes/rant:

- Currently most other apps do not target Android 11 so they work fine. But starting November 2021, all apps will be required to target it. 
- AFAIK it won't be possible to install fully working file manager on Android TV 11 (if the app was updated after November) - there's new permission for that but that permission requires the use of Storage Access Framework
- Q: Why is there no Storage Access Framework on Android TV? "...certain product teams have decided that these intents are not needed on their products (such as watches and TVs)..." ([Google Issue Tracker](https://issuetracker.google.com/issues/71327396))
- How others are dealing with that: [Nova Video Player](https://github.com/nova-video-player/aos-AVP/issues/336)

**Comment by moneytoo** [comment]
> So what's the final verdict on this? Will we be getting a library like MX anytime soon?

I think it's like that. I personally feel very little need for a media library so I have no drive to create it.

> The system file chooser can't ignore .nomedia files

When I put `.nomedia` file in a folder with videos, it **does** hide it from the list of folders in the [Video view](https://github.com/moneytoo/Player#i-prefer-using-media-library-instead-of-a-file-chooser) of the default chooser.

> I'd just like to have all my movies (both in Internal and SD) in one place.

This is actually fixable - just buy a high end phone and you won't have SD card (😉). I also find the directory structure on a file system more customizable - I can choose if I want to have one or two levels of depth.

**Comment by moneytoo** [comment]
Here's another ExoPlayer/Media3 based & FOSS Android video player which offers video library - https://github.com/anilbeesetti/nextplayer
