### ISSUE TITLE
Some Queries Regarding Hardware and Software Decoding

### ISSUE THREAD

**Issue by MercerBoi** [moneytoo/Player#142]
So, I indulge in a lot of 10bit x265 / HEVC media and previous experiences have determined that software decoding of these files results in a massive battery drain, whereas hardware decoding has a considerably lower impact.

Although the description for this player does mention that it supports `H.265 HEVC`, I would like to know that means specifically, is it saying that the app makes use of the hardware to decode the files?

Could there be a way to know when HW decoding is being used and when SW decoding is used?

**Comment by moneytoo** [comment]
For video, Just Player (because it uses ExoPlayer) basically always uses device decoders. (The only exception is AV1 on devices older than Android 10.) In most cases, device decoder should mean HW decoder, but not necessarily (but then there's no HW decoder at all).

You may also check:

- #50
- https://exoplayer.dev/battery-consumption.html
- https://github.com/google/ExoPlayer/issues/3039#issuecomment-314042014

In your case, HEVC media should use your device decoder (most probably HW).

**Comment by MercerBoi** [comment]
Ah, I understand. Thank you for clarifying.
