### ISSUE TITLE
external subtitles file bug shows unknown!

### ISSUE THREAD

**Issue by RanbirSingh** [moneytoo/Player#16]
First of all man you did a great job. there is small bug on external .srt file it shows unknown in list(Redmi Phone)

**Comment by moneytoo** [comment]
Hi. What's the subtitle file name?

**Comment by RanbirSingh** [comment]
> Hi. What's the subtitle file name?

Hi, let me give you more details i have downloaded the external subtitles file .srt i have picked with long click and it added that file in subtitles selection button..but it shows unknown and also external subtitles also not worked! i am using ANDROID 10

**Comment by moneytoo** [comment]
There's language detection from the subtitle filename - that's why I asked about that. I improved it in a recent change (it will be available in the next update) but I'm not 100% sure it's the same case. If you share subtitle file here or send it to me privately (email from my Github profile), it would allow me to verify that.

**Comment by RanbirSingh** [comment]
Hi Marcel language bug is fixed it worked perfectly. Thanks for this amazing Video player

**Comment by moneytoo** [comment]
Thank you for a confirmation!
