### ISSUE TITLE
Video Pauses when starting playback

### ISSUE THREAD

**Issue by ZEPLUMBER1** [moneytoo/Player#215]
Video Pauses itself each time you start to play something

**Comment by brentonv** [comment]
This issue is already open:

Auto play #179

**Comment by ZEPLUMBER1** [comment]
I edited and removed what was mentioned on this issue

I somehow missed it, thanks.

**Comment by moneytoo** [comment]
Is this caused by the [Auto frame rate matching](https://github.com/moneytoo/Player#:~:text=Auto%20frame%20rate%20matching.)? Does it work (start the playback) when you disable it? If yes, than it is the same issue as in #179. In this case, please provide me a [bug report](https://github.com/moneytoo/Player/issues/179#issuecomment-1004428016).
