### ISSUE TITLE
Does not start playing automatically

### ISSUE THREAD

**Issue by SubZero77** [moneytoo/Player#241]
The player does not automatically start playing the video, and waiting for the "Play" button to be pressed.  For example, if you make it the default player in LazyMedia Deluxe...and in other programs too... It decreases usability :((
My device is Ugoos-AM6, ATV, Android 9

**Comment by moneytoo** [comment]
Is this caused by the [Auto frame rate matching](https://github.com/moneytoo/Player#:~:text=Auto%20frame%20rate%20matching.)? Does it work (start the playback) when you disable it? If yes, than it is the same issue as in #179. In this case, please provide me a [bug report](https://github.com/moneytoo/Player/issues/179#issuecomment-1004428016).
