### ISSUE TITLE
Split APKs

### ISSUE THREAD

**Issue by chromer030** [moneytoo/Player#244]
Please split APKs by target architecture in order to reduce installed size.
Or please provide both Universal APK and splitted APKs.

**Comment by moneytoo** [comment]
I partially thought about this in #119. The vast majority of users download the app from Google Play where it's already delivered with architecture binaries only so it's circa 24 MB instead of 56 MB. I see the releases here useful mostly for debugging/bisecting some issues and not as a major release channel. Furthermore multiple APK variants could complicate the choice for inexperienced users.
