### ISSUE TITLE
MiXplorer as Document Provider

### ISSUE THREAD

**Issue by DarremMolko** [moneytoo/Player#283]
I was testing this player https://github.com/mo3rfan/syncplayer/ and when I went to pick a local file I noticed it uses the native file manager, but what caught my attention is that MiXplorer appears there as a document provider/file chooser. Would it be possible to have Just Player access MiXplorer file chooser too? 

"Seleccionar" ("Choose")
![Screenshot_20220226-145718](https://user-images.githubusercontent.com/70179709/155854263-ff2c8288-349c-4435-a16b-c6ffff33e04e.png)

**Comment by moneytoo** [comment]
SyncPlayer uses different intent, `ACTION_GET_CONTENT` instead of `ACTION_OPEN_DOCUMENT`, while the latter provides significant advantages such as preselecting initial/starting folder, acquiring long term/persistent access to files or filtering multiple mime types. Document Providers are listed when using `ACTION_OPEN_DOCUMENT` but what MiXplorer provides isn't really a it.

**Comment by DarremMolko** [comment]
I think Just Player is perfect the way it is right now and the use of ACTION_OPEN_DOCUMENT is definitely more convenient. I'll be closing this issue.
