### ISSUE TITLE
Audio Sync issue using Just Player with Syncler

### ISSUE THREAD

**Issue by gwilly7** [moneytoo/Player#291]
I am using the Beta version of Just Player in Syncler on a Sheild Pro and have notice audio sync issues the last week or so. I have primarily been watching the new season of Last Kingdom when I notice the issue but plays fine in their built in exo player.

**Comment by gwilly7** [comment]
I have found on Reddit from others with the issue that if you skip either forward or backwards the issue is resolved

**Comment by Nuklear92** [comment]
I second this issue! Just started experiencing, this happens mostly when Auto Framerate Matching is turned ON. At least on my personal experience, it seems like when the player triggers the Framerate switch sometimes it have a negative effect of A/V Sync and when the content start playing the audio is lagging behind and as you said, a simple press to rewind the video does help the audio and video to be in sync again. However, it's quite annoying specially when you're binge watching a series or just watching a few videos back to back and the framerate matching is triggered. Then you have to press rewind almost every time. 


Also, another issue I found is when Auto Framerate Matching is ON and the video playing is already matched with the display, if you press fast forward (FF) or just skip forward anything one time, the whole video start to stutter super bad and in order to fix it you need to skip backwards one time. Super annoying, specially if you wanna quickly jump skip some boring part of a video but then have to rewind back and watch the boring part because the video starts stuttering badly. 😩

**Comment by moneytoo** [comment]
I'm afraid there's not much to do in Just Player as the whole AV sync is already managed by ExoPlayer.
