### ISSUE TITLE
Auto-detect rotation

### ISSUE THREAD

**Issue by UnlimitedCookies** [moneytoo/Player#305]
Currently, when you play a horizontal video the player starts in landscape mode and then the player starts sensing that the phone is hold upright, starting the rotate animation each time you open a new video.

I guess you could fix this in two ways:

1. Read the video metadata before opening the player and then starting out in the video's rotation

2. Use information from the gyroscope to set the default orientation, like many apps do.

**Comment by Fmoment1** [comment]
> Currently, when you play a horizontal video the player starts in landscape mode

Strange, I'm not experiencing this. Every video starts in portrait mode if I'm holding the phone upright. I'm on version 0.111 (latest build as of 5th May, 2022).

**Comment by UnlimitedCookies** [comment]
I am still on 0.104, because that's the latest release on F-Droid. But have there been changes to the rotation mechanics since then?

**Comment by Fmoment1** [comment]
I don't know, I just relayed what my experience is. I'm on the Play Store version.

**Comment by moneytoo** [comment]
> Read the video metadata before opening the player and then starting out in the video's rotation

Accessing files is heavy async operation and generally it shouldn't block UI especially app launch. I also experienced this issue with the animation before so I opted for landscape mode as default (cause most movies/shows are landscape) because of this. Anyway, in the latest versions of Android the app startup looks ok IMHO.
