### ISSUE TITLE
F-Droid Updates

### ISSUE THREAD

**Issue by realmain** [moneytoo/Player#34]
Looks like F-Droid can't build correctly because you changed your versioning.

It's currently stuck on v0.12. Your newer versions go by: 0.13, 0.14, 0.15

Instead of: v0.13, v0.14, v0.15

**Comment by moneytoo** [comment]
F-Droid doesn't build this app automatically and manual update/merge is required. It's because of srclibs versioning, but I want to ask them and verify that.

Change of tag versions is intentional test. It looks to me that if I leave auto update check on and F-Droid detects an update, it removes the app from "Latest". I will verify that and return to original versioning.

Due to the delays, I'm planning on updating the F-Droid version once every 2 weeks to 1 month.

**Comment by moneytoo** [comment]
Tags are back to their original naming and latest release was submitted for inclusion to F-Droid.
