### ISSUE TITLE
ffmpeg decoder still has image noise, blue screen

### ISSUE THREAD

**Issue by DinhLap96** [moneytoo/Player#341]
App No support: 
http://113.163.216.23:1935/live/tv2.stream/playlist.m3u8

ffmpeg decoder still has image noise, blue screen

**Comment by shockergit** [comment]
![Screenshot_20220814-133254_Just Player](https://user-images.githubusercontent.com/63154802/184532940-ceb1428c-24b8-4367-b726-80a6e748b102.jpg)
shows fine here

**Comment by moneytoo** [comment]
The stream doesn't really work for me, probably because of my location, but when it does, it works fine. FFmpeg technically doesn't decode video as ExoPlayer uses basically only device decoders. Noise could be caused by lower quality stream which could be possibly auto selected based on current network condition.

**Comment by DinhLap96** [comment]
The apps I've tried all run smoothly, only in the market project

Vào CN, 14 thg 8, 2022 vào lúc 17:33 shock ***@***.***> đã
viết:

**Comment by DinhLap96** [comment]
Stable quality video source, I tried it with some other apps it plays very
smoothly


Vào Th 3, 16 thg 8, 2022 vào lúc 02:05 Marcel Dopita <
***@***.***> đã viết:
