### ISSUE TITLE
[Feature Request] External subtitles active by default

### ISSUE THREAD

**Issue by joaopedromfigueiredo** [moneytoo/Player#39]
I use this app in Android TV 9, it is the best. I watch a lot of movies and shows in free time and all of them have external subtitles, but always I have to load them. 
Imagining that if always have an external subtitles, the user always has preference for them, since he had to insert it. Can you could add a feature that external subtitles are active by default?

**Comment by moneytoo** [comment]
As the player doesn't request any permission, it doesn't have access to any other file except the one from file chooser. But this is definitely something I would like to improve too. I have few ideas that I want to try (from technical side) to see what would be the best solution.

**Comment by kyelbek** [comment]
Whether you make a change here or not, it would be cool if player could switch to just loaded subtitles without further interaction.

P.S. I'm glad I found your app on F-Droid. I didn't know that ExoPlayer library is so powerful and there are actually community movie player apps using it. This is what I was looking for a very long time after MX Player became Indian crapware. VLC on the other hand has its own issues, so I ditched watching offline movies until I find something else. And so far, this is brilliant. Simple and fast. Thanks!

**Comment by moneytoo** [comment]
Available since version 0.24 currently [pre-release](https://github.com/moneytoo/Player/releases). Try loading subtitle manually as usual and you will be prompted to grant the app access to a folder containing your videos. Videos and subtitles need to be somewhere in this folder (or any sub folder) for auto load to work. Granting access to whole storage can cause little delays (depending on how you open and select videos).
