### ISSUE TITLE
Question: next video button 

### ISSUE THREAD

**Issue by venkat2305** [moneytoo/Player#430]
How can I enable the next video button

**Comment by moneytoo** [comment]
The next button is accessible only at the end of the a video. Also in the first press, you will have to grant the player access to the scope of folders you are using as the next button will only work in this scope.

**Comment by VasilisKos** [comment]
> The next button is accessible only at the end of the a video. Also in the first press, you will have to grant the player access to the scope of folders you are using as the next button will only work in this scope.

I think it'd be much more practical if a "next" and a "previous" button appeared when the opened video is in a folder that contains more videos. And they should appear whenever the touchscreen is tapped, not only when the video ends.

P.S. I've also reported an issue with the "delete" button not appearing (#422).

**Comment by venkat2305** [comment]
> The next button is accessible only at the end of the a video. Also in the first press, you will have to grant the player access to the scope of folders you are using as the next button will only work in this scope.

Can you please tell me how I can give access to the scope of the folder? @moneytoo

**Comment by george-emerald** [comment]
Please push an update for the next/previous buttons to appear constantly. It's useless otherwise. Nobody watches the credits waiting for it to appear. The only solution now is to exit and manually open the next video. If not as a default option please enable something like `Persistent next/previous buttons` in the settings. I don't understand how a button that only appears at the end of the video is in any way functional.

**Comment by znh339** [comment]
Please update so that the Next/Previous buttons appear permanently. The button that appears at the end has little functionality. Thank you
