### ISSUE TITLE
MediaCodecVideoRendererError MPEG4

### ISSUE THREAD

**Issue by RexusWolf** [moneytoo/Player#443]
**Describe the bug**
While trying to reproduce a video, I'm getting this error in my Firestick.

`MediaCodecVideoRenderer error, index=0, format-Format(0, null, null, video/mp4v-es, null, -1, null, [640, 272, -1.0), (-1,-1)), format_supported=YES`

If I click on the Details button of the error, I get the message:

`Decoder failed: OMX.MTK.VIDEO.DECODER.MPEG4`

**To Reproduce**
1. Open a video in Just Video Player
2. See error

**Expected behavior**
Video reproduces without problems.

**Device (please complete the following information):**
 - Model: Fire TV
 - OS: Fire OS
 - Version 7.6.2.4

**Media**

**Additional context**

**Comment by sigma2017** [comment]
I am encountering a similar  issue with a mkv remux converted to dolby vision profile 8.1 but not from the beginning. 1st time happened after around 15 minutes and the again after another 10. Unfortunately i had to switch to Nova Player in order to watch the movie.
More and more problems with the latest releases :(
Using latest v0.138 installed from google play on my Philips 48OLED807.

**Comment by sigma2017** [comment]
https://mega.nz/file/YY9l2ZIK#tzbkG5lEuqGJt5y7Q-fy7HuA08o-OTmUf4Z1XmezmDQ
Here you have a sample attached, made with mkvtoolnik from the original file.
Thank you.
