### ISSUE TITLE
[Request] WSA Compatibility 

### ISSUE THREAD

**Issue by song2daodao** [moneytoo/Player#446]
**Description**
Now I'm using multiple monitors and when I drag justplayer to the second monitor, the app will refresh and pause the currently playing video. According to the developers of WSA, this need to be addressed by the app developers
https://github.com/microsoft/WSA/issues/236
![QQ截图20230307122439](https://user-images.githubusercontent.com/99074946/223320436-649df61f-b2d8-4384-9730-5fc84f3169f0.png)
I will be very grateful if you are willing to do it. And please add the function of "force auto-load subtitles with the same name / remember the playback speed". I had to repeat these two steps every time when I switched to the next video. Thank you very much!!

**Comment by moneytoo** [comment]
I was able to replicate and fix the issue in [v0.142](https://github.com/moneytoo/Player/releases/tag/v0.142). In my case the issue was because of `touchscreen` configuration even though neither my laptop nor the connected display supports it. Feel free to test it if this fixes your issue as well. In theory there could be also issues with changing dpi, but handling that could be not that trivial.

I'm finally allowed to publish Just Player to Amazon Appstore on Windows 11 so I already submitted it there.
