### ISSUE TITLE
Battery consumption

### ISSUE THREAD

**Issue by Lucky390163** [moneytoo/Player#553]
Just player is using much battery.It consumes 1 percent battery in 10 min.

While in other hand vlc consumes 1 percent battery in 41 min.Please see this my battery still not drained even it is 63% i am currently using.![Screenshot_20240201_162554_VLC.jpg](https://github.com/moneytoo/Player/assets/115852216/dc17b57b-2b00-4ce3-8928-ad79e0d9c32a)

![Screenshot_20240201_162205_Digital Wellbeing.jpg](https://github.com/moneytoo/Player/assets/115852216/d128edea-f827-4a9f-862c-e3c59da522f4)

I have enabled this option called full acceleration in vlc and it is working fine using much battery.

**Comment by moneytoo** [comment]
> Just player is using much battery.It consumes 1 percent battery in 10 min.
> 
> While in other hand vlc consumes 1 percent battery in 41 min.

In other words, you are saying that with VLC, your battery lasts ove 68 hours? That seems little over board, even with 6000 mAh battery.

I would recommend replicating your issue in the [ExoPlayer Demo app](https://github.com/androidx/media/tree/release/demos) or [Next Player](https://github.com/anilbeesetti/nextplayer/) as Just Player doesn't do much more.

Otherwise it's the same issue as in #393.

**Comment by Lucky390163** [comment]
No i mean basic consumption of vlc is 20 min as same as my Samsung default video player do.

My phone total video playtime is 23 hours or more mentioned in website.

My audio playback time is upto 110 hours mentioned in website.![Screenshot_20240201_223535_Brave.jpg](https://github.com/moneytoo/Player/assets/115852216/e991306c-50ae-41a1-9a9f-410f86d9bf4c)

My default video player is better than other players.
