### ISSUE TITLE
[Bug] Xiaomi TV Box S 2nd Gen. auto framerate switching doesnt work

### ISSUE THREAD

**Issue by shruggie1** [moneytoo/Player#566]
**Describe the bug**
I have the Xiaomi TV Box S 2nd Gen. and the auto framerate switching doesnt work.

**To Reproduce**
1. Open Just Player and go to advanced settings.
2. Check if auto framerate switching is enabled
3. Go back and open a video
4. Check TV info. TV stays at 60Hz but video file is 24Hz.

**Expected behavior**
The TV should change to 24Hz.

**Device (please complete the following information):**
 - Model: Xiaomi TV Box S 2nd Gen.
 - OS: Android TV 11
 - Version 0.155

**Comment by brentonv** [comment]
Your TV also needs to support this

**Comment by mo123** [comment]
> Sure, my TV supports that. Tested with Nvidia Shield TV.

You have to complain to Xiaomi since they haven't implemented auto frame-rate switching in the 2nd Gen Mi Box S's firmware. If enough people report it, they might fix it.

As a workaround you can buy TvQuickActions, enable auto frame-rate switching there and use apps like TiviMate, Vimu Video Player or SmartTube. They are the only 3 apps that will support it with TvQuickAction's custom implementation of auto frame-rate switching. Just Video Player, Kodi, Nova Video Player and other apps still have no solution.

**Comment by shruggie1** [comment]
Thanks for the explanation. Didnt know that the Xiaomi firmware is here the problem.

**Comment by Smultie** [comment]
> I have similar issue with ccwgtv 4k.
> 
> Frame rate switching works on exoplayer, kodi and libvlc.

Same thing here. I'm pretty sure Auto Frame-rate Switching does work on this device, since other players/apps provide this functionality.
I use Just player as an external player in Stremio, and although Just Player works better than the built-in player, I do miss the auto-refreshrate.

**Comment by moneytoo** [comment]
Closing this stale issue as it won't be possible for me to reproduce it. When I used Mi Box S 1st gen, switching worked fine for me.
