### ISSUE TITLE
[BUG] - title bar inaccessible for viewing mediainfo 

### ISSUE THREAD

**Issue by JonathanAkaJD** [moneytoo/Player#572]
**Describe the bug**
Unable to navigate up to the title with a remote in order to long press and bring up media info.(I have the latest media info apk installed as required)

**To Reproduce**
Try to navigate upwards to the title with a remote control. You will be unable to navigate up beyond the play/pause button that appears in the center of the screen.

**Expected behavior**
Be able to navigate up to the title area and longpress without using some kind of mouse toggling.(Did not test to see if this would work. Don't currently have a mouse toggle app at my disposal.)

**Device:**
 - Model: Nvidia Shield Pro(2019)
 - OS: Android 11
 - Version 0.159

**Additional context**
Can longpress with finger on my Google pixel 6 pro. With that said, it doesn't seem like the media data is being passed to the media info app on a pixel 6 pro(android 14 / player build 0.159). It opens the mediainfo app but says you must at least open one file. So it seems like there could be more than one bug related to viewing mediainfo regardless of device.

**Comment by githottub** [comment]
I can confirm this. I also can't navigate up to the title using the remote. Because of that, I thought maybe the intended way to bring up media info was long pressing on the video file name in the folder view. But that didn't work... which is why I previously posted [Bug] MediaInfo #565 

In other words, it seems that if using a remote it is currently impossible to trigger this feature.

App Version: 0.155
OS: Android 12
Device: 2023 model TV running Google TV

**Comment by moneytoo** [comment]
Yeah, the title bar is not focusable on TV so it's not possible to launch external app. It's more like a hidden shortcut, not really suitable to replicate on TV. 
Maybe somewhere else, but another issue is that MediaInfo doesn't analyze network streams which is probably what most use.
