### ISSUE TITLE
Q: Why github version behind playstore ??

### ISSUE THREAD

**Issue by SamRezaXYZ** [moneytoo/Player#616]

**Comment by moneytoo** [comment]
There are no differences in the code except for version change. Google suddenly rejected an update because...

> The functionality of your app doesn't work as described in the store listing. Make sure to test your app on a variety of TV devices and configurations.
> * For example, **your app does not provide video content as described on the store listing**.

I ask and tried to resolve that and ended up removing all store description translations, and adding following:

> This app doesn't provide any video content by itself. It can only access and play content provided by the user.

But changing description isn't enough and Google also requires uploading new app release, even though nothing but version changed.

To this day I'm still confused what would make you think that a video player comes with content or what line promises that. I guess we live in the streaming age now and a local video player app is some bizzare antique tool.
